name: Python CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.0'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up the environment
      run: |
        set FLASK_APP=website
        set DATABASE_URL=sqlite:///test_db.sqlite

    - name: Run Tests
      env:
        FLASK_ENV: testing
      run: |
        pytest --disable-warnings --maxfail=5

